language: python
python:
  - 3.5
addons:
  apt:
    packages:
    - libev4
    - libev-dev
cache: pip
env:
  - CASSANDRA_DRIVER="3.7.1"
  - CASSANDRA_DRIVER="2.7.2"
services:
  - cassandra
install:
  - pip install cassandra-driver==$CASSANDRA_DRIVER
  - pip install cqlsh
script:
  - cqlsh -f schema.cql
  - python run.py
